[theme]
primaryColor       = "#C8102E"
backgroundColor    = "#F4F5F7"
secondaryBackgroundColor = "#FFFFFF"
textColor          = "#111827"
font               = "sans serif"

[server]
headless           = true
enableCORS         = true
enableXsrfProtection = true
port               = 8501
maxUploadSize      = 50

[browser]
gatherUsageStats   = false

[ui]
hideTopBar         = true
